### ISSUE TITLE
The v1.0-alpha seems to be a debug build.

### ISSUE THREAD

**Issue by ohrn** [wulkanat/EDDX52#1]
After installing your DLL, EDDiscovery pops up a message saying the program can't start because MSVCP140**D**.dll is missing.

Seems the EDDX52.dll is a debug build which makes it a bit fiddly to run without the full Visual Studio environment installed, as the D version of MSVCP140.dll is not available separately.

A new build in release mode would be great, I'd love to try  out your project.

Regards,
ohrn

**Comment by Theaninova** [comment]
Oh, ok, thank you for informing me. I have literally no experience in sharing my project with others, so I didn't know that it makes such a difference. I now did a build on release configuration, please try it out and tell me if it works for you: [https://1drv.ms/u/s!Aq8Kg0iqxkdrgp8k5xRjXcCz9T67Rw](url)

**Comment by ohrn** [comment]
Yes, the new DLL works. Nice!

Now I just have to figure out the rather obtuse action system in EDDiscovery.

Also, I can only seem to set one led in a "program", only the first setLED call has any effect.

**Comment by Theaninova** [comment]
Please try to use the advSetLED command, I haven't looked into the setLED command for a while, so it might be just bugged.

**Comment by ohrn** [comment]
advSetLED has the same problem, in a program like this only the first line has any effect

PROGRAM LedTest

DLLCall EDDX52, advSetLED, 12, 1
DLLCall EDDX52, advSetLED, 9, 1

END PROGRAM

**Comment by Theaninova** [comment]
I discovered a potential cause and hopefully fixed it: [https://1drv.ms/u/s!Aq8Kg0iqxkdrgp8k5xRjXcCz9T67Rw](url) Please note that I am not a huge Elite Player (In fact I don't even have EDDiscovery installed), I just enjoy making these little tools, so I didn't test it. But theoretically it should work.

**Comment by ohrn** [comment]
The new version didn't make a difference but I just noticed EDDiscovery prints the following message in the log:

Error: DLL EDDX52: UCCESS
At Step 1 in X52::LedTest:1: DLLCall

Perhaps there is an off by one error somewhere...

**Comment by Theaninova** [comment]
It's not an error (It is supposed to say **S**UCCESS). Can you please try out the MFD functions? Because that would show me wether the plugin crashed or if there is a more general issue with the LEDs.

**Comment by ohrn** [comment]
Same problem with setString and other MFD functions, only the first line executes.

I've also tried the various reset commands, same same there. I think it's a general problem with all calls.

**Comment by Theaninova** [comment]
Ok, maby the problem is that "SUCCESS" is falsly recognized as an error. I made it a blank String, maby that will help: [https://1drv.ms/u/s!Aq8Kg0iqxkdrgp8k5xRjXcCz9T67Rw](url)

**Comment by ohrn** [comment]
Ok, I'll give the new version a try tomorrow. However looking at the documentation here:

https://github.com/EDDiscovery/EDDiscoveryAdditionalDLLs/blob/3a3410669d810ecb9d35d7dfcdc9093535404e49/ExampleAddInDLL/Win64DLL/EDDInterface64.h#L92

I think you have to return a string starting with + to make it work, e.g. +SUCCESS. An empty string will probably also cause an error.

**Comment by Theaninova** [comment]
Ahhhhh, ok, that would explain it. I changed it, try this one: [https://1drv.ms/u/s!Aq8Kg0iqxkdrgp8k5xRjXcCz9T67Rw](url)

**Comment by ohrn** [comment]
+SUCCESS! :)

Multiple LED and MFD commands now work. With the exception getLinesCount which returns garbage.

**Comment by Theaninova** [comment]
Yay! Check out the release tab, I just pushed a new version, which theoretically should fix this issue.

**Comment by ohrn** [comment]
getLinesCount still doesn't work in the new release, other than that it's fine.

Looking at your change you forgot to add a + to the start of the string returned by getLinesCount.

**Comment by Theaninova** [comment]
You are completeley right, Hotfix is out.
